language: python

python:
  - "2.7"

install:
  - pip install --requirement dev-requirements.txt
  - pip install coveralls

script:
  - coverage run --omit="setup.py" --source="." $(which trial) tests && coverage report
  - flake8 .

after_success:
  - coveralls
